version: "3.5"

services: 
  weather-now:
    image: node:16-alpine
    container_name: weather-now
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    command: sh bin/start.sh
